spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lrbj/config-repo
          username: lrbj

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/

