spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lrbj/config-repo
          username: lrbj
          password: 31gsy11023
          basedir: D:\learn\spring cloud\test\data

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"



