spring:
  application:
    name: order

  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
 # jpa:
  #  show-sql: true
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

